// src/components/EasyTable/EasyTable.tsx
import React from 'react';
import ReactMarkdown from 'react-markdown';

interface EasyTableProps {
  header: string[];
  data: Array<Array<string | React.ReactNode>>;
  columnWidths?: { [key: string]: string };
  center?: boolean;
  lineOnly?: boolean;
}

const EasyTable = ({
  header,
  data,
  center = false,
  columnWidths = {},
  lineOnly = false,
}: EasyTableProps) => {
  const getColumnWidthStyle = (columnName: string) => ({
    width: columnWidths[columnName] || '100%',
  });

  const renderCellContent = (cellData: any) => {
    if (typeof cellData.props?.href !== 'undefined') {
      return <a href={cellData.props.href}>{cellData.props.children}</a>;
    }

    if (typeof cellData === 'object') {
      return <a href={cellData.link}>{cellData.title}</a>;
    }

    if (typeof cellData === 'string') {
      if (cellData.startsWith('http')) {
        return <a href={cellData}>Website</a>;
      }
      if (cellData.includes('\n')) {
        const lines = cellData.split('\n');
        return lines.map((line, index) => (
          <div key={index} className={index < lines.length - 1 ? 'easy-cell-line' : 'easy-cell-line-last'}>
            <ReactMarkdown>{line}</ReactMarkdown>
          </div>
        ));
      }
      return <ReactMarkdown>{cellData}</ReactMarkdown>;
    }
    return cellData;
  };

  return (
    <div className={`easy-wrapper ${center ? 'easy-center' : ''}`}>
      <div
        className="easy-header"
        style={{
          background: lineOnly ? 'none' : undefined,
          borderBottom: lineOnly ? 'none' : undefined,
        }}
      >
        {header.map((column, index) => (
          <div key={index} style={getColumnWidthStyle(column)}>
            {column}
          </div>
        ))}
      </div>
      {data.map((row, rowIndex) => (
        <div
          className="easy-row"
          key={rowIndex}
          style={{
            background: lineOnly ? 'none' : undefined,
            borderTop: lineOnly ? '2px solid var(--sl-color-hairline)' : undefined,
          }}
        >
          {row.map((cell, cellIndex) => (
            <div key={cellIndex} style={getColumnWidthStyle(header[cellIndex])}>
              {renderCellContent(cell)}
            </div>
          ))}
        </div>
      ))}
    </div>
  );
};

export default EasyTable;

// docs/.vitepress/components/EasyTable.vue
<template>
  <div class="easy-table-wrapper">
    <table class="easy-table">
      <thead>
      <tr>
        <th v-for="column in visibleColumns" :key="column.name" :style="{ width: column.width }">
          {{ column.header || column.name }}
        </th>
      </tr>
      </thead>
      <tbody>
      <tr v-for="(row, rowIndex) in data" :key="rowIndex">
        <td v-for="column in visibleColumns" :key="column.name">
          <span v-html="renderCellContent(row[column.name])"></span>
        </td>
      </tr>
      </tbody>
    </table>
  </div>
</template>

<script>
import { marked } from "marked";

export default {
  name: 'EasyTable',
  props: {
    columns: {
      type: Array,
      required: true
    },
    data: {
      type: Array,
      required: true
    }
  },
  computed: {
    visibleColumns() {
      return this.columns.filter(column =>
          this.data.some(row => column.name in row)
      );
    }
  },
  methods: {
    renderCellContent(content) {
      if (content === undefined) return '';

      if (typeof content === 'object' && content !== null) {
        if (content.link && content.title) {
          return `<a href="${content.link}">${content.title}</a>`;
        }
        // Convert the object to a formatted JSON string and wrap it in a code block
        const jsonString = JSON.stringify(content, null, 2);
        return `<pre><code>${jsonString}</code></pre>`;
      }

      if (typeof content === 'string') {
        if (content.startsWith('http')) {
          return `<a href="${content}">Link</a>`;
        }
        return marked.parse(content);
      }
      return content;
    },
  }
};
</script>

<style scoped>
.easy-table-wrapper {
  width: 100%;
  overflow-x: auto;
}

.easy-table {
  display: table;
  width: 100%;
}

.easy-table tr:last-child td {
  border-bottom: none;
}

.easy-table td > code {
  display: inline-block;
  overflow-x: auto;
  white-space: pre;
  max-width: 100%;
}
</style>
